version: "3.7"
services:
  application:
    container_name: app
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=password
  mysql:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password